### ISSUE TITLE
能不能给个上传的demo

### ISSUE THREAD

**Issue by tsztodd** [tickstep/aliyunpan-api#2]

**Comment by abadfox233** [comment]
可以参考这篇文章：
https://ironblog.cn/archives/golang-shang-chuan-wen-jian-zhi-a-li-yun-pan

**Comment by xiaoyaofenfen** [comment]
可以参考下我们另一个仓库的代码：https://github.com/tickstep/aliyunpan/blob/main/internal/command/upload.go
